name: CI

on: [pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - run: sudo bundle install

      # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode
      - run: sudo xcode-select -s /Applications/Xcode_12_beta.app

      - run: bundle exec fastlane unit_tests
        env:
          SCHEME: HelloCI280820
